apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" (include "librenms.fullname" . ) "init"}}
  labels:
    app.kubernetes.io/name: {{ template "librenms.name" . }}
    helm.sh/chart: {{ template "librenms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  init.sh: |-
{{ tpl (.Files.Get "files/init.sh") . | indent 4 }}
  username: {{ .Values.gui.username | quote }}