apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-%s" (include "librenms.fullname" .) "poller" }}
  labels:
    app.kubernetes.io/name: {{ include "librenms.name" . }}
    helm.sh/chart: {{ include "librenms.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.poller.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "librenms.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "librenms.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ printf "%s-%s" (include "librenms.fullname" .) "poller" }}
          image: {{ printf "%s:%s" .Values.poller.image.repository .Values.poller.image.tag | quote }}
          imagePullPolicy: {{ .Values.gui.nginx.image.pullPolicy }}
          command: ["python3"]
          args: ["/opt/librenms/librenms-service.py", "-d"]
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" (include "librenms.fullname" . ) "env" }}
          env:
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  {{- if .Values.mariadb.enabled }}
                  name: {{ template "librenms.mariadb.fullname" . }}
                  {{- else }}
                  name: {{ .Values.externalDatabase.password }}
                  {{ end }}
                  key: mariadb-password
            - name: APP_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "librenms.fullname" . }}
                  key: app-key
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "librenms.redis.fullname" . }}
                  key: redis-password
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.uid
          volumeMounts:
            - name: librenms-config
              mountPath: /opt/librenms/config.d
      volumes:
        - name: librenms-config
          configMap:
            name: {{ include "librenms.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
